#pragma once

typedef enum {
    SYSCALL_THREAD_EXIT,
    SYSCALL_LOG_WRITE,
    SYSCALL_GET_TIME,
    SYSCALL_NAMESPACE_CREATE,
    SYSCALL_HANDLE_CREATE,
    SYSCALL_HANDLE_CLOSE,
    SYSCALL_VM_CREATE,
    SYSCALL_VM_CLONE,
    SYSCALL_VM_MAP,
    SYSCALL_VM_MAP_VDSO,
    SYSCALL_VM_MOVE,
    SYSCALL_VM_REMAP,
    SYSCALL_VM_UNMAP,
    SYSCALL_VM_WRITE,
    SYSCALL_VM_FILL,
    SYSCALL_VM_READ,
    SYSCALL_IO_ENABLE,
    SYSCALL_IO_DISABLE,
} syscall_vec_t;
