#pragma once

#define SYSCALL_THREAD_EXIT 0L
#define SYSCALL_GET_NANOSECONDS_SINCE_BOOT 1L
#define SYSCALL_THREAD_YIELD 2L
#define SYSCALL_NAMESPACE_CREATE 3L
#define SYSCALL_NAMESPACE_CLONE 4L
#define SYSCALL_NAMESPACE_ADD 5L
#define SYSCALL_NAMESPACE_REMOVE 6L
#define SYSCALL_NAMESPACE_RESOLVE 7L
#define SYSCALL_VMM_CREATE 8L
#define SYSCALL_VMM_CLONE 9L
#define SYSCALL_VMM_MAP 10L
#define SYSCALL_VMM_REMAP 11L
#define SYSCALL_VMM_MOVE 12L
#define SYSCALL_VMM_UNMAP 13L
#define SYSCALL_VMM_READ 14L
#define SYSCALL_VMM_WRITE 15L
#define SYSCALL_SET_REAL_TIME 16L
#define SYSCALL_MEMORY_WAIT 17L
#define SYSCALL_MEMORY_WAKE 18L
