#pragma once

#define SYSCALL_THREAD_EXIT 0l
#define SYSCALL_GET_NANOSECONDS_SINCE_BOOT 1l
#define SYSCALL_THREAD_YIELD 2l
#define SYSCALL_NAMESPACE_CREATE 3l
#define SYSCALL_NAMESPACE_CLONE 4l
#define SYSCALL_NAMESPACE_ADD 5l
#define SYSCALL_NAMESPACE_REMOVE 6l
#define SYSCALL_NAMESPACE_RESOLVE 7l
