#pragma once

#define VEC_DIVIDE_ERROR 0
#define VEC_DEBUG 1
#define VEC_NMI 2
#define VEC_BREAKPOINT 3
#define VEC_OVERFLOW 4
#define VEC_UNDEFINED_OPCODE 6
#define VEC_DEVICE_UNAVAILABLE 7
#define VEC_DOUBLE_FAULT 8
#define VEC_INVALID_TSS 10
#define VEC_INVALID_SEGMENT 11
#define VEC_STACK_FAULT 12
#define VEC_GENERAL_FAULT 13
#define VEC_PAGE_FAULT 14
#define VEC_FPU_ERROR 16
#define VEC_ALIGNMENT_ERROR 17
#define VEC_MACHINE_CHECK 18
#define VEC_SIMD_ERROR 19
#define VEC_VIRTUALIZATION_ERROR 20
#define VEC_CONTROL_PROTECTION_ERROR 21

#define VEC_DEVICE_MIN 0x20
#define VEC_DEVICE_MAX 0xf9

#define VEC_IRQ_TIMER 0xfa
#define VEC_IPI_SHOOTDOWN 0xfb
#define VEC_IPI_YIELD 0xfc
#define VEC_IPI_PANIC 0xfd
#define VEC_IRQ_APIC_ERR 0xfe
#define VEC_IRQ_SPURIOUS 0xff
